WARNING:werkzeug: * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
INFO:werkzeug: * Running on http://192.168.1.80:5000/ (Press CTRL+C to quit)
INFO:app_ex:Main request successfull
INFO:werkzeug:127.0.0.1 - - [29/Nov/2022 23:56:21] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [29/Nov/2022 23:56:26] "[33mGET /heath HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [29/Nov/2022 23:56:29] "[33mGET /heathz HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [29/Nov/2022 23:56:35] "[33mGET /hstatus HTTP/1.1[0m" 404 -
INFO:app_ex:Status request successfull
INFO:werkzeug:127.0.0.1 - - [29/Nov/2022 23:56:39] "GET /status HTTP/1.1" 200 -
WARNING:werkzeug: * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
INFO:werkzeug: * Running on http://10.152.122.172:3111/ (Press CTRL+C to quit)
INFO:werkzeug:192.168.1.80 - - [30/Nov/2022 16:10:37] "GET / HTTP/1.1" 200 -
INFO:werkzeug:192.168.1.80 - - [30/Nov/2022 16:10:37] "GET /static/css/main.css HTTP/1.1" 200 -
INFO:werkzeug:192.168.1.80 - - [30/Nov/2022 16:10:37] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
INFO:werkzeug:192.168.1.80 - - [30/Nov/2022 16:10:44] "GET / HTTP/1.1" 200 -
INFO:werkzeug:192.168.1.80 - - [30/Nov/2022 16:10:44] "[36mGET /static/css/main.css HTTP/1.1[0m" 304 -
ERROR:app:Exception on /1 [GET]
Traceback (most recent call last):
  File "C:\Users\ekint\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ekint\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ekint\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ekint\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ekint\nd064_course_1-main\project\techtrends\app.py", line 46, in post
    app.loger.debug('Article id $post_id returned')
    ^^^^^^^^^
AttributeError: 'Flask' object has no attribute 'loger'
INFO:werkzeug:192.168.1.80 - - [30/Nov/2022 16:10:47] "[35m[1mGET /1 HTTP/1.1[0m" 500 -
DEBUG:app:The "About US" page is retrieved
INFO:werkzeug:192.168.1.80 - - [30/Nov/2022 16:10:58] "GET /about HTTP/1.1" 200 -
INFO:werkzeug:192.168.1.80 - - [30/Nov/2022 16:10:58] "[36mGET /static/css/main.css HTTP/1.1[0m" 304 -
WARNING:werkzeug: * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
INFO:werkzeug: * Running on http://192.168.1.80:3111/ (Press CTRL+C to quit)
INFO:werkzeug:192.168.1.80 - - [30/Nov/2022 16:12:33] "GET / HTTP/1.1" 200 -
INFO:werkzeug:192.168.1.80 - - [30/Nov/2022 16:12:33] "[36mGET /static/css/main.css HTTP/1.1[0m" 304 -
INFO:werkzeug:192.168.1.80 - - [30/Nov/2022 16:12:34] "GET /1 HTTP/1.1" 200 -
INFO:werkzeug:192.168.1.80 - - [30/Nov/2022 16:12:34] "[36mGET /static/css/main.css HTTP/1.1[0m" 304 -
DEBUG:app:Article not found
INFO:werkzeug:192.168.1.80 - - [30/Nov/2022 16:12:40] "[33mGET /9 HTTP/1.1[0m" 404 -
INFO:werkzeug:192.168.1.80 - - [30/Nov/2022 16:12:40] "[36mGET /static/css/main.css HTTP/1.1[0m" 304 -
